### ISSUE TITLE
Create CLI

### ISSUE THREAD

**Issue by guidiego** [getappa/appa#1]
We need to create a CLI for APPA, the CLI needs to call an extern function that will execute the job, the reason for that is our intentions in export it using an API in the future to integrate with some interfaces :)

## Create task
*struct*
`appa new task <name> <cmd> <path>`

*sample*
`appa new task collector python test/collector.py`

**should create in inside *tasks* in *config.yml***
```yaml
tasks:
  - name:  collector
    command: python
    path: test/collector.py
```

## Create entity
*struct*
`appa new processor <name>` 

*sample*
`appa new processor user` 

**should create in inside *processors* in *config.yml***
```yaml
processors:
  - name: user
    id_prop: ''
    collector_tasks: {}
    sync_tasks: {}
    async_tasks: {}
```

## Link Task -> Entity
*struct*
`appa link <task>:<prop> <entity> <type>` 

*samples*
`appa link collector:_ user collector_tasks` 
`appa link synctask:my_sync user sync_tasks` 
`appa link asynctask:my_async user async_tasks` 

**should create in inside *processors* in *config.yml***
```yaml
processors:
  - name: user
    id_prop: ''
    collector_tasks:
      collector: _
    sync_tasks: 
      synctask: my_sync
    async_tasks:
      asynctask: my_async
```

## Set storage uri
*struct*
`appa set_storage <uri>`

*sample*
`appa set_storage path/storage`

```yaml
storage_uri:  path/storage
tasks:
   # ....
processors:
   # ....
```
