### ISSUE TITLE
Create Distributed Systems 

### ISSUE THREAD

**Issue by guidiego** [getappa/appa#10]
I want to be able to export a task as a "Server Task" with one or more endpoints, or only a socket connection that emit an event. I need to be able to call this endpoint get response and exec the same pipeline than Command :)

```yaml
- name: myapitask
  command: !api #this will make rust post into the endpoint in 'path'
  path: myendpoint.com
```

The same for `!socket`
