### ISSUE TITLE
Reduce database

### ISSUE THREAD

**Issue by guidiego** [getappa/appa#6]
First, we need to register reduce tasks, this tasks will receive all Rocks DB entity, and will return a big map of values to override this old DB.

```yaml
processors:
   - name: any
     reduce_tasks:
       - my_reduce
```

This reduce will happen sync as sync_tasks, but this time we will get ALL data not only one line, and will save the hole return overriding the database.
